In [1]:
pip install torch

In [2]:
import torch


#create a tensor

In [3]:
t1 =torch.empty(3)
t1

tensor([2.6353e-08, 4.4502e-41, 1.9767e-24])

In [4]:
t1.dtype

torch.float32

In [6]:
t2=torch.empty(3,dtype=torch.int)
t2

tensor([635855024,         0, 765947136], dtype=torch.int32)

In [7]:
t3 = torch.rand(5,4,3)
t3

tensor([[[0.3722, 0.2462, 0.7121],
         [0.7020, 0.2523, 0.5559],
         [0.1530, 0.7764, 0.6078],
         [0.7947, 0.9241, 0.2938]],

        [[0.8051, 0.2908, 0.9918],
         [0.2038, 0.1554, 0.7048],
         [0.8546, 0.6589, 0.3954],
         [0.9910, 0.5199, 0.6012]],

        [[0.6818, 0.4963, 0.2446],
         [0.6391, 0.9004, 0.8728],
         [0.7451, 0.5257, 0.5078],
         [0.6592, 0.8570, 0.7940]],

        [[0.8158, 0.4800, 0.5471],
         [0.9045, 0.2509, 0.0134],
         [0.5928, 0.7705, 0.0928],
         [0.5337, 0.9946, 0.4888]],

        [[0.0272, 0.4413, 0.4214],
         [0.7176, 0.1270, 0.2332],
         [0.2518, 0.6885, 0.5146],
         [0.7492, 0.6390, 0.7523]]])

In [8]:
t3.dtype

torch.float32

In [9]:
t4 =torch.randint(0,20,[5,4])
t4

tensor([[12,  8, 11, 12],
        [ 8,  4,  3,  9],
        [11,  7, 14,  1],
        [18, 11, 10,  4],
        [ 7, 14, 13,  8]])

In [12]:
t5 = torch.zeros(2,3)
t5

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
t6=torch.ones([2,3,4],dtype=torch.int)
t6

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)

In [16]:
t6.size()

torch.Size([2, 3, 4])

In [17]:
t6.dim()

3

In [18]:
import numpy as np


In [19]:
arr = np.ones([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
t7 = torch.tensor(arr)
t7

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Implace operator

In [21]:
t8= torch.ones(2,3,dtype=torch.int)
t8

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [23]:
t9=torch.ones(2,3,dtype=torch.int)
t9 =torch.add(t8,t9)
t9

tensor([[2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

In [24]:
t9.sub(t8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

Reshaping the tensors

In [26]:
t7.size()
torch.Size([2,3])

torch.Size([2, 3])

In [27]:
t7.reshape(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

tensor broadcasting

In [29]:
t7.size()

torch.Size([2, 3])

In [30]:
t6.size()

torch.Size([2, 3, 4])

In [32]:
t12 =torch.add(t7,t6)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 2

In [33]:
x=torch.empty(5,4,3,1)
y=torch.empty(1,3,5)
z=torch.add(x,y)
z.size()

torch.Size([5, 4, 3, 5])

Vector multiplication

In [37]:
A =torch.tensor([[10,5,5,6]])
B=torch.tensor([[50],[120],[574],[80]]) # Corrected tensor creation
C=torch.mul(A,B)
C

tensor([[ 500,  250,  250,  300],
        [1200,  600,  600,  720],
        [5740, 2870, 2870, 3444],
        [ 800,  400,  400,  480]])

Transpose

In [38]:
x= torch.randint(0,20,[4,5])
x

tensor([[12,  7,  6,  4,  8],
        [ 7, 14, 16,  1, 16],
        [ 7, 15, 10,  1, 13],
        [11, 11, 15,  0, 10]])

In [39]:
y=torch.transpose(x,0,1)

In [40]:
x.size()

torch.Size([4, 5])

In [41]:
y

tensor([[12,  7,  7, 11],
        [ 7, 14, 15, 11],
        [ 6, 16, 10, 15],
        [ 4,  1,  1,  0],
        [ 8, 16, 13, 10]])

Indexing and slicing

In [42]:
y

tensor([[12,  7,  7, 11],
        [ 7, 14, 15, 11],
        [ 6, 16, 10, 15],
        [ 4,  1,  1,  0],
        [ 8, 16, 13, 10]])

In [43]:
y[0][0].item()

12

In [45]:
t13=torch.rand(5,4,7)
t13

tensor([[[9.7573e-01, 1.6922e-04, 7.1631e-01, 5.4810e-02, 5.9965e-01,
          7.9279e-01, 6.4275e-01],
         [4.9239e-02, 9.2138e-01, 1.4723e-01, 5.0062e-01, 6.7294e-01,
          4.1314e-01, 6.5549e-01],
         [9.2957e-02, 9.0033e-01, 3.8712e-01, 9.7015e-01, 5.8916e-01,
          8.0574e-01, 8.4667e-01],
         [3.5016e-01, 3.3419e-01, 4.9941e-01, 1.4535e-01, 2.5821e-01,
          4.7656e-01, 8.0487e-01]],

        [[4.7829e-01, 5.5624e-01, 6.7783e-01, 5.2652e-01, 6.3687e-01,
          6.4344e-01, 4.3216e-01],
         [8.3991e-01, 4.5515e-01, 5.7223e-01, 6.9151e-01, 7.0060e-02,
          9.9521e-01, 4.9458e-01],
         [6.5013e-01, 2.6417e-01, 1.7963e-01, 3.8839e-01, 7.2911e-01,
          9.8984e-01, 1.0909e-01],
         [4.2296e-01, 1.1285e-01, 3.5297e-02, 1.6824e-01, 5.1906e-02,
          1.5581e-01, 9.4518e-01]],

        [[2.7191e-01, 1.5943e-01, 4.4088e-01, 9.2923e-01, 7.8015e-01,
          6.8933e-01, 1.1647e-01],
         [4.8860e-01, 1.5143e-01, 2.3891e-01, 2.739

In [46]:
t13[4]

tensor([[0.2514, 0.1037, 0.3788, 0.4235, 0.2635, 0.2963, 0.5648],
        [0.3399, 0.3255, 0.0066, 0.9594, 0.3104, 0.2621, 0.8762],
        [0.7775, 0.2546, 0.4602, 0.9777, 0.5166, 0.2517, 0.1442],
        [0.9360, 0.3012, 0.6939, 0.8654, 0.1303, 0.1564, 0.8826]])

In [47]:
t13[4][3]

tensor([0.9360, 0.3012, 0.6939, 0.8654, 0.1303, 0.1564, 0.8826])

In [48]:
t13[1:3]

tensor([[[0.4783, 0.5562, 0.6778, 0.5265, 0.6369, 0.6434, 0.4322],
         [0.8399, 0.4551, 0.5722, 0.6915, 0.0701, 0.9952, 0.4946],
         [0.6501, 0.2642, 0.1796, 0.3884, 0.7291, 0.9898, 0.1091],
         [0.4230, 0.1128, 0.0353, 0.1682, 0.0519, 0.1558, 0.9452]],

        [[0.2719, 0.1594, 0.4409, 0.9292, 0.7801, 0.6893, 0.1165],
         [0.4886, 0.1514, 0.2389, 0.2740, 0.2535, 0.3008, 0.7778],
         [0.1588, 0.5419, 0.8853, 0.3691, 0.3677, 0.3363, 0.2456],
         [0.3397, 0.9579, 0.5899, 0.1862, 0.8656, 0.2582, 0.7186]]])

Reverse indexing

In [49]:
t13[::-1]

ValueError: step must be greater than zero

In [50]:
y

tensor([[12,  7,  7, 11],
        [ 7, 14, 15, 11],
        [ 6, 16, 10, 15],
        [ 4,  1,  1,  0],
        [ 8, 16, 13, 10]])

In [51]:
y=torch.flip(y,[0,1])

In [52]:
y

tensor([[10, 13, 16,  8],
        [ 0,  1,  1,  4],
        [15, 10, 16,  6],
        [11, 15, 14,  7],
        [11,  7,  7, 12]])